<?php

namespace BCLib\Tests;

use Symfony\Contracts\HttpClient\ResponseInterface;

class MockHTTPClient extends \Symfony\Component\HttpClient\MockHttpClient
{
    public $last_method;
    public $last_uri;
    public $last_options;

    public function request(
        string $method,
        string $url,
        array $options = []
    ): ResponseInterface {
        $this->last_method = $method;
        $this->last_uri = $url;
        $this->last_options = $options;
        return parent::request($method, $url, $options); // TODO: Change the autogenerated stub
    }
}